In [2]:
from game_env import GameEnv
import constants
from bot_game import BotGame
import pandas as pd
import numpy as np
from gym import spaces
import gym
from collections import Counter

In [3]:
env = gym.make('CartPole-v1')

In [4]:
env.observation_space

Box(4,)

In [5]:
env.reset()

array([ 0.04425034, -0.00019404, -0.03799084,  0.0214096 ])

In [ ]:
my_game = BotGame(2, 4)

In [ ]:
observation, reward = my_game.game_state_reward()

In [ ]:
len(observation)

In [ ]:
observation_reset = my_game.reset()
len(observation_reset)

In [ ]:
list(observation_reset.keys())

In [ ]:
obs_space = my_game.create_observation_space()

In [ ]:
len(obs_space.spaces)

In [ ]:
list(obs_space.spaces.keys())

In [ ]:
list(zip(list(obs_space.spaces.keys()), list(observation_reset.keys())))

In [ ]:
my_game.create_observation_space()

In [ ]:
# str(my_game.current_player.current_city)
start_city = my_game.city_dict['chennai']
str(start_city)

In [ ]:
[str(x) for x in my_game.current_player.cards()]

In [ ]:
city_dist = my_game.shortest_paths(start_city)

In [ ]:
city_dist

In [ ]:
max([*city_dist.values()])

In [ ]:
new_reward_level = 0
color_rewards = [0, 0, 5, 10, 15, 20] + [20] * (constants.HAND_SIZE_LIMIT - 5)
for player in [*my_game.player_dict.values()]:
    card_colors = [card.color for card in player.player_hand.hand]
    card_colors = Counter(card_colors)
    print(card_colors.values())
    new_reward_level += sum([color_rewards[count] for count in card_colors.values()])
new_reward_level

In [ ]:
a = [1,2,3,4]
a[:-1]

In [ ]:
a = np.empty((3,2), dtype=object)

In [ ]:
a[2,0] = start_cty

In [ ]:
a

In [9]:
from numpy import load

data = load('expert_pendulum.npz')
lst = data.files
for item in lst:
    print(item)
    print(len(data[item]))
    print(data[item])

actions
20000
[[ 1.9979553 ]
 [ 1.9569684 ]
 [ 1.191274  ]
 ...
 [-0.4524516 ]
 [-0.45245433]
 [-0.45245484]]
obs
20000
[[ 9.9722856e-01  7.4399039e-02 -8.9499897e-01]
 [ 9.9887246e-01  4.7474675e-02 -5.3950638e-01]
 [ 9.9931651e-01  3.6966346e-02 -2.1035510e-01]
 ...
 [ 9.9589729e-01  9.0490736e-02 -1.7677716e-07]
 [ 9.9589729e-01  9.0490736e-02  1.3501312e-07]
 [ 9.9589729e-01  9.0490744e-02  4.0573592e-08]]
rewards
20000
[-0.0896396  -0.03519198 -0.00721119 ... -0.00841573 -0.00841574
 -0.00841574]
episode_returns
100
[-1.67989636e+00 -2.34948650e+02 -1.21171991e+02 -1.20521779e+02
 -1.19788683e+02 -1.22824949e+02 -1.18820483e+02 -1.18580149e+02
 -1.24781061e+02 -1.15759465e+02 -2.21630026e+02 -1.17066681e+02
 -1.15420523e+02 -2.35858447e+02 -1.21483178e+02 -2.26669387e+02
 -1.20018324e+02 -2.55397097e+00 -1.21544349e+02 -1.23187212e+02
 -1.17826321e+02 -1.20175512e+02 -1.20939559e+02 -2.25162842e+02
 -1.22160798e+02 -3.17475876e+02 -1.20159795e+02 -1.15017261e+02
 -1.19739268e+02 -

In [30]:
from numpy import load

data = load('../logs/expert_pandemic.npz')
lst = data.files
for item in lst:
    print(item)
    print(len(data[item]))
    print(data[item])

actions
160
[[  0]
 [ 11]
 [  5]
 [109]
 [  5]
 [109]
 [  0]
 [ 12]
 [  0]
 [ 11]
 [  0]
 [ 10]
 [  0]
 [ 56]
 [  0]
 [ 57]
 [  5]
 [109]
 [  0]
 [ 13]
 [  0]
 [ 17]
 [  5]
 [109]
 [  5]
 [110]
 [  5]
 [110]
 [  5]
 [110]
 [  0]
 [ 53]
 [  5]
 [109]
 [  5]
 [109]
 [  0]
 [ 28]
 [  0]
 [ 25]
 [  0]
 [ 24]
 [  0]
 [ 25]
 [  5]
 [111]
 [  5]
 [111]
 [  0]
 [ 11]
 [  5]
 [109]
 [  5]
 [109]
 [  0]
 [ 12]
 [  0]
 [ 28]
 [  0]
 [ 30]
 [  0]
 [ 31]
 [  5]
 [111]
 [  5]
 [109]
 [  0]
 [ 13]
 [  0]
 [ 17]
 [  5]
 [109]
 [  5]
 [111]
 [  5]
 [111]
 [  0]
 [ 32]
 [  0]
 [ 30]
 [  0]
 [ 14]
 [  0]
 [ 13]
 [  0]
 [ 17]
 [  5]
 [109]
 [  0]
 [ 11]
 [  5]
 [109]
 [  5]
 [109]
 [  0]
 [ 23]
 [  5]
 [109]
 [  5]
 [109]
 [  0]
 [ 18]
 [  0]
 [ 20]
 [  0]
 [ 25]
 [  5]
 [111]
 [  5]
 [111]
 [  0]
 [ 28]
 [  0]
 [ 35]
 [  5]
 [108]
 [  0]
 [ 38]
 [  0]
 [ 40]
 [  0]
 [ 11]
 [  5]
 [109]
 [  5]
 [109]
 [  0]
 [ 12]
 [  0]
 [ 24]
 [  0]
 [ 25]
 [  5]
 [111]
 [  5]
 [111]
 [  5]
 [109]
 [  0]
 [ 13]
 [  0]
 

In [31]:
2 ** 3

8